rvm:
  - 1.8.7
  - 1.9.3
  - rbx
  - ree
  - jruby
#  - ruby-head
notifications:
  recipients:
    - kou@cozmixng.org
before_install:
  - travis/before_install.sh
before_script:
  - travis/before_script.sh
